# Generated by Django 4.2.6 on 2024-03-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0051_alter_profile_key_alter_profile_ky'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
