# Generated by Django 4.2.6 on 2024-03-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0052_profile_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='views_count',
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('authorview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorview', to=settings.AUTH_USER_MODEL)),
                ('postview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postview', to='userartist.profile')),
            ],
        ),
    ]
