# Generated by Django 4.2.6 on 2024-03-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0053_remove_profile_views_count_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='View1',
        ),
    ]
