# Generated by Django 4.2.6 on 2024-03-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0054_rename_view_view1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view1',
            name='views_count',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
