# Generated by Django 4.2.6 on 2024-03-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0055_alter_view1_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view1',
            name='views_count',
            field=models.CharField(max_length=250),
        ),
    ]
