# Generated by Django 4.2.6 on 2024-03-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0058_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='authorlike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='postlike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='userartist.profile'),
        ),
    ]
