# Generated by Django 4.2.6 on 2024-03-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0059_alter_like_authorlike_alter_like_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_count', models.IntegerField(default=0)),
                ('authorFollow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorfollow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
