# Generated by Django 4.2.6 on 2024-03-27 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userartist', '0061_rename_authorfollow_follow_authorfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='authorfollow1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authorfollow1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
