# Generated by Django 4.2.6 on 2024-03-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadmusic', '0006_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
    ]
